all:
  children:
    dev:
      hosts:
        vm1:
          ansible_host: 127.0.0.1
        # vm2:
      vars:
        ansible_user: user
        ansible_ssh_private_key_file: "{{private_key_path}}"
        ansible_ssh_port: 22