---
- name: Create user prometheus
  ansible.builtin.user:
    name: prometheus
    shell: /sbin/nologin
    system: true
    create_home: false
    state: present

- name: Ensure destination folder exists
  ansible.builtin.file:
    path: /etc/prometheus
    state: directory
    mode: '0755'
    owner: prometheus
    group: prometheus

- name: Ensure destination folder exists
  ansible.builtin.file:
    path: /var/lib/prometheus
    state: directory
    mode: '0755'
    owner: prometheus
    group: prometheus

- name: Download Prometheus
  ansible.builtin.get_url:
    url: 'https://github.com/prometheus/prometheus/releases/download/v3.4.1/prometheus-3.4.1.linux-amd64.tar.gz'
    dest: '/tmp/prometheus.tar.gz'

- name: Unpack Prometheus
  ansible.builtin.unarchive:
    src: /tmp/prometheus.tar.gz
    dest: "{{prometheus_path}}"
    remote_src: true
    extra_opts: [--strip-components=1]
    owner: prometheus
    group: prometheus

- name: Coppy binary
  ansible.builtin.copy:
    src: /etc/prometheus/prometheus
    dest: /usr/local/bin/prometheus
    owner: prometheus
    group: prometheus
    mode: '0755'
    remote_src: true

- name: Copy configuration
  ansible.builtin.copy:
    src: prometheus.yml
    dest: /etc/prometheus
    owner: "{{prometheus_user}}"
    group: "{{prometheus_group}}"
  notify: Restart prometheus

- name: Deploy Prometheus systemd service
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    mode: '0644'
  notify: Restart prometheus

- name: Enable prometheus
  ansible.builtin.systemd:
    name: prometheus
    enabled: true
    state: started

- name: Health check prometheus
  ansible.builtin.uri:
    url: "http://127.0.0.1:9090/-/healthy"
    return_content: true
  register: healthcheck

- name: Show healthcheck
  ansible.builtin.debug:
    var: healthcheck.content