---
# tasks file for blackbox-exporter

- name: Create group
  ansible.builtin.group:
    name: "{{ blackbox_group }}"
    state: present

- name: Create user
  ansible.builtin.user:
    name: "{{blackbox_user}}"
    group: "{{blackbox_group}}"
    shell: /sbin/nologin
    create_home: false
    state: present

- name: Ensure destination folder exists
  ansible.builtin.file:
    path: "{{item}}"
    owner: "{{blackbox_user}}"
    group: "{{blackbox_group}}"
    mode: "0755"
    state: directory
  loop:
    - "{{blackbox_path}}"
    - "{{blackbox_config_path}}"

- name: Download blackbox resource
  ansible.builtin.get_url:
    url: 'https://github.com/prometheus/blackbox_exporter/releases/download/v0.26.0/blackbox_exporter-0.26.0.linux-amd64.tar.gz'
    dest: /tmp/blackbox.tar.gz
 
- name: Extract blackbox
  ansible.builtin.unarchive:
    src: /tmp/blackbox.tar.gz
    dest: "{{blackbox_path}}"
    remote_src: yes
    extra_opts: [--strip-components=1]
    owner: "{{ blackbox_user }}"
    group: "{{ blackbox_group }}"

- name: Create synlink for blackbox-exporter binary
  ansible.builtin.file:
    src: "{{blackbox_path}}/blackbox_exporter"
    path: "{{blackbox_bin}}"
    owner: "{{blackbox_user}}"
    group: "{{blackbox_group}}"
    mode: "0755"
    state: link

- name: Copy config to blackbox config path
  ansible.builtin.copy:
    src: config.yml
    dest: "{{blackbox_config_path}}/config.yml"
    owner: "{{blackbox_user}}"
    group: "{{blackbox_group}}"
    mode: "0644"
  notify: Restart blackbox-exporter

- name: Deploy blackbox-exporter systemd service
  ansible.builtin.template:
    src: blackbox-exporter.service.j2
    dest: /etc/systemd/system/blackbox-exporter.service
    mode: '0644'
    owner: "{{blackbox_user}}"
    group: "{{blackbox_group}}"
  notify: Restart blackbox-exporter


